### ISSUE TITLE
Overwriting files

### ISSUE THREAD

**Issue by emeybee** [nextcloud/integration_google#112]
Not an issue but a question, I'm just setting up Nextcloud and trying to import my data from Google using this integration but it is copying very slowly. I have an older copy of a lot of the data that's already elsewhere on my server-- if I copy that to Nextcloud directly, is the integration smart enough to recognize the existing files and not write over them unless the Drive version is newer?

**Comment by emeybee** [comment]
So it does not seem to be so smart... it's just making copies of everything with a suffix added. Is there any solution to this? I don't want to have to wait weeks for it to download 700+ GB when I already have 600+ GB of those files on my server in another share.

**Comment by eneiluj** [comment]
Hey, it's supposed to download a file only if it does not exist or if the drive one is more recent than the local one.

What is the added suffix?
Which version of the app are you using?

**Comment by julien-nc** [comment]
The name suffix was added because google allows multiple files with the same name in a directory...

v1.0.9 (coming soon) will include improvements in this area: the suffix will only be added for files with name conflicts (on the google side).
So if you already have part of your files with original names in NC, this import will correctly skip existing files.
