### ISSUE TITLE
Google Photos : stucks at 0%

### ISSUE THREAD

**Issue by ghost** [nextcloud/integration_google#115]
Hi !

I'm trying to import my google photos with this app.
But actually, it's stuck.

>1189 Photos Google (>1 GiB)
0 photo importée

I don't have anything to debug or any message.
Do you have an idea?

Thank you!
Erwan

**Comment by eneiluj** [comment]
Any error in the server logs?

**Comment by rwanito** [comment]
For contacts I have :
`Could not load event listener service OCA\\Maps\\Listener\\CardCreatedListener: Could not resolve logger! Class \"logger\" does not exist. Make sure the class is auto-loadable by the Nextcloud server container`
I cut the message because it's massive. But no problem with contacts.

And for Photos, I don't find any clear traces of "Photos", "Google Photos", in the logs.
But I got this : 
"message": "Taille du fichier attendue : 996 octets mais taille du fichier lue (depuis le client Nextcloud) et \u00e9crit (dans le stockage Nextcloud) : 0 octet. Cela peut \u00eatre un probl\u00e8me de r\u00e9seau au niveau du client ou un probl\u00e8me de stockage au niveau du serveur.",

In english, it means something like : 
It got 996 bytes but the file size received from nextcloud is 0 byte. Problably due to the nextcloud store.

Everything is clear in my server, but do you think it may come from my reverse proxy ?


Thank you !

**Comment by Enelar** [comment]
Same issue with helm chart. I thought it was on my side.
Next cloud 24.0.3-apache

**Comment by Enelar** [comment]
Fixed by increasing php memory limit in configs

**Comment by rwanito** [comment]
Hey!
I have this in my php.ini
```
upload_max_filesize=5G
post_max_size=5G
memory_limit=20G
```

And it changes nothing :(

Is it possible to do with google takeout and then uploading them ?

Thanks you

**Comment by Enelar** [comment]
I've found the api https://gist.github.com/stewartmcgown/7f5dcbf4ccd385637786f9581b620e6a
But it's much easier to log in to your server, and download the archieve for yourself:
https://webapps.stackexchange.com/questions/123300/how-to-programmatically-create-download-google-takeout-archive

**Comment by julien-nc** [comment]
A fix is potentially coming in the next release. If you want to test it: https://github.com/nextcloud/integration_google/issues/35#issuecomment-1361381136

**Comment by mcortinas** [comment]
hi all,

I have the same issue and I think this is a pity due to i think it's a powerful tool in order to use more NextCloud and less Google. I tried several times and ways last 3 months without lucky... Sometimes I've seen some photo imported but less than 60.... the most of times stuck in 0% and 0 photos imported....

Let me show my environment
```
sudo -u www-data php /opt/nextcloud/occ status --output=json_pretty
{
    "installed": true,
    "version": "25.0.4.1",
    "versionstring": "25.0.4",
    "edition": "",
    "maintenance": false,
    "needsDbUpgrade": false,
    "productname": "Nextcloud",
    "extendedSupport": false
}
```
this is the volume to import
```
 >69542 Google photos (>64 GiB)

0 photos imported
Photo import background process will begin soon. You can close this page. You will be notified when it finishes.
```

I tried to increase php values without luchy....
```
upload_max_filesize=5G
post_max_size=5G
memory_limit=20G
```
1. Let me share nextcloud.log file starting Photo Importing with app - integration_google: 1.0.9 [afterPushButtonImportGooglePhotos.tar.gz](https://github.com/nextcloud/integration_google/files/10830938/afterPushButtonImportGooglePhotos.tar.gz)
2. I also upgraded integration_google to [v1.0.9-2-nightly](https://github.com/nextcloud/integration_google/releases/download/v1.0.9-2-nightly/integration_google-1.0.9-2-nightly.tar.gz) but I can see the menu changes from Data migration to Google Synchronization but I receive an error , it seems something related on javascript, let me attach an screenshoot.
![Screenshot_20230225_093955](https://user-images.githubusercontent.com/692263/221353670-a70d909a-3437-44e4-8a98-6ebf3554ad95.png)

**Comment by mcortinas** [comment]
Let me share more, I ran another instance of Nextcloud in my rapsberrypi4 but this time with docker, [i launched the all-in-one with docker-compose with more lucky, this time has been imported 4k images in 6hours, more or less.... ](https://github.com/nextcloud/all-in-one)

**Comment by etuckeriv** [comment]
I was having this issue and figured out it was because my cron jobs weren't configured properly. I also installed the nightly version, but it still didn;t work until I got my cron job set up correctly, so I'm not sure that was necessary.

**Comment by slkwilly19** [comment]
Is someone hacking my phone because this stuff is on my phone I need some kind of help because I don't know nothing. No computers or phones

**Comment by N-Soder** [comment]
Hi All, 

I'm running into this issue also, had no problem importing contacts however been suck at 0% for the last couple hours, did a cancel and re-import to no effect, happy to try something else if people have any ideas. 

Cheers

**Comment by janeoa** [comment]
Same issue, stuck at 0 photos

` Error   PHP   Error: dns_get_record(): A temporary server error occurred. at /var/www/html/lib/private/Http/Client/DnsPinMiddleware.php#83 at       2023-03-22T07:11:06+00:00
                lib/private/Log/ErrorHandler.php line 92

                 0. <<closure>>
                    OC\Log\ErrorHandler::onError(
                      2,
                      "dns_get_record(): A temporary server error occurred.",
                      "\/var\/www\/html\/lib\/private\/Http\/Client\/DnsPinMiddleware.php",
                      83
                    )
                 1. lib/private/Http/Client/DnsPinMiddleware.php line 83
                    dns_get_record("photoslibrary.googleapis.com", 16)`

**Comment by marcelklehr** [comment]
Hey everyone! Could you please try again with the latest version?
