### ISSUE TITLE
Low resolution images when importing from Google Photos

### ISSUE THREAD

**Issue by Ruzken** [nextcloud/integration_google#32]
**Problem**
Images imported from google photos have lower resolution than original. Imported videos have a size of arround 50 KB and cannot be oppened.

Example resolution:
Image in Google Photos: 4000x3000
Image imported to Nextcloud: 512 x 384

**Current Setup**
Nextcloud 20.0.1
Ubuntu 20.04
Google integration 0.0.22

**Comment by eneiluj** [comment]
Thanks a lot for the bug report. I didn't notice the low resolution as I only tested with small pics... It's fixed in v0.0.23. It's not possible to get the original files with the API but we get:
* photo at the same resolution as the original
* "high quality, transcoded version of the original video" API doc

I'm interested to know if it works fine on your side.

**Comment by Ruzken** [comment]
It's working fine for me now.

Thank you for your great work!

**Comment by SimonStefan** [comment]
I had the same issue a month ago and managed to import most of my photos manually with Google Drive. Thanks for fixing it! The smaller sizes are still used next to the import button in the settings where it says e.g. `~18279 Google photos (~17 GiB)`. Should be around 100GiB for me.

This information would be valuable in the Readme
```
- photo at the same resolution as the original
- "high quality, transcoded version of the original video" API doc
```

Is there any other solution to get the original photos than Google Takeout? Do you have a plan to support this method?

**Comment by eneiluj** [comment]
@SimonStefan It's not possible to get any size information in Photos API. The given estimation is very basic and considers a photo is 1 Mo in average (which is better than nothing but far from correct :grin:).

> Is there any other solution to get the original photos than Google Takeout?

What do you mean? Do you mean that it's possible to get original photo files with Google Takeout?

**Comment by SimonStefan** [comment]
I can confirm as well that the import is using much larger images now, but before you start the sync, you need to delete the smaller images that were imported before the bug was fixed.

> > Is there any other solution to get the original photos than Google Takeout?
> 
> What do you mean? Do you mean that it's possible to get original photo files with Google Takeout?

I haven't tried it but it is mentioned here: https://support.google.com/photos/thread/146373?hl=en&msgid=16413363

It would be nice to have a direct download to Nextcloud with unpacking instead of download the data to my machine and upload it again.

Should I create another issue with a feature request for Google Takeout to discuss this further?
