### ISSUE TITLE
Google Drive Sync fails to sync on files

### ISSUE THREAD

**Issue by moekify** [nextcloud/integration_google#53]
Nextcloud v21

Docker Setup with Redis & Cron running

I'm trying to import a Google Drive and I receive plenty of errors like this one

![image](https://user-images.githubusercontent.com/19408385/109185353-38fc8000-7790-11eb-9ea9-98604e7b18ea.png)

Hence, not all files are imported. Anything I can do here?

**Comment by eneiluj** [comment]
Could you send me one of those files so I try to reproduce the problem?

**Comment by moekify** [comment]
E.g. this image 
![Poster-2-big](https://user-images.githubusercontent.com/19408385/109210183-c8b02780-77ac-11eb-8cc7-98a7ae0192be.jpg)
But it's also loads of files unfortunately. Images, presentations, etc. 

Total Import would be 16GB, it managed to 3.1GB and then seems to only have errors

**Comment by eneiluj** [comment]
Thanks. I've uploaded it in my drive and then the import is successful.
I just want to make sure the issue is not related to the files themselves.

Your logs are showing that the destination file can't be opened via `fopen` which leads to a `null` file resource and then the HTTP client crashes.

Did you just start the import and wait or did you run it several times, canceled and rerun, stuff like that?

Is the file `Ifmeeting8feb19 -2.jpg` created and empty or just absent on Nextcloud side?

**Comment by moekify** [comment]
Hey! 
Sorry was out over the weekend. 

Thanks for trying this out :) I had to restart the job at least once because there was an issue first with our cron setup. 

Is there a way to clear "cache" if this is the issue?

**Comment by digitalrevisor** [comment]
hi @moekify, sorry to go off topic. that cron setup you are mentioning, does that run a command to automatically import google drive files so one dont have to push the button all the time? or is it the one for cron.php?

**Comment by moekify** [comment]
> 
> 
> hi @moekify, sorry to go off topic. that cron setup you are mentioning, does that run a command to automatically import google drive files so one dont have to push the button all the time? or is it the one for cron.php?

Sorry didn't notice this earlier! 
It's for the cron.php
