### ISSUE TITLE
Calendar sync not working Nextcloud - google

### ISSUE THREAD

**Issue by digitalrevisor** [nextcloud/integration_google#54]
Google integration and Google oauth is installed and tested.  
Together with Deck,  Tasks and Apointments this is a genious feature.
This works: 
Manually import / fetch activities FROM google TO Nextcloud calandar.
This works NOT:
Manually import /send activities FROM Nextcloud calandar TO google calandar.

Automatic calandar syncing doesnt work at all.

Is it an idea to create an integrated calendar app inside Nextcloud iOS og Android client - and let google calendar /outlook on river?   
Ive tried DAVx and Tasks / Etar calendar but that doesnt sync properly. 

Any comments?

**Comment by digitalrevisor** [comment]
You pay 5 Euro for One calandar android for this feature. iOS alternativ is not discovered. Any comment?

**Comment by jdaviescoates** [comment]
> You pay 5 Euro for One calandar android for this feature. iOS alternativ is not discovered. Any comment?

I'm not the developer, but I've no idea what you are saying/ asking here (so I'm not sure they will either) :)

**Comment by jdaviescoates** [comment]
I'm really like the new Google Integration stuff, but yes, it'd be much better and more useful if it were possible to actually sync Nextcloud and Google Calendars rather than just being able to manually import Calendars from Google into Nextcloud.

As a first step it'd be nice if it could just automatically import Google Calendars everyday rather than having to manually click the button everyday to avoid missing stuff that's be added on Google.

But yeah, more long term hopefully the plan is to enable fully automated syncing in both directions (so that edits made  on Nextcloud to imported Google Calendars also get pushed back to Google).

**Comment by jdaviescoates** [comment]
> But yeah, more long term hopefully the plan is to enable fully automated syncing in both directions (so that edits made on Nextcloud to imported Google Calendars also get pushed back to Google).

And, just to add, it seems that right now I am unable to delete calendar events which have been imported via Google, which is somewhat frustrating, as I now have a load of cancelled events that are no longer displayed in my Google Calendar appearing on my Nextcloud Calendar and with no way (as far as I can tell) or removing them.  I guess I may have to delete the whole calendar within Nextcloud and then re-import it, but that seems like overkill just to clean up a few unwanted events...

**Comment by eneiluj** [comment]
Hey, sorry for the late answer.
The purpose of this app is to **import/migrate** data from google, not to sync it.
It can make a "one shot" import and that's it. The extra fancy detail is that if you import a calendar that already exists in NC, missing events will be added. The opposite is not true, deleted events on google side won't be deleted on NC side.
I'm sure you have good reasons to expect calendars sync and have them in 2 places. Sorry it will never be done by this app.
