### ISSUE TITLE
Status code 403

### ISSUE THREAD

**Issue by lipunis** [nextcloud/integration_google#62]
https://pastenow.ru/cfddddc942a3819152a8937adc3cace8   How I can kill whis bug?

**Comment by eneiluj** [comment]
It seems that you didn't add the required APIs ("Google Drive API", "Google Calendar API", "People API" and "Photos Library API") to your Google OAuth app.
Or maybe you connected to your google account in NC while those APIs were not added yet.

You can try to:
* go to any google page (gmail, GDrive...) and log out
* make sure you added the APIs in your OAuth app
* try to connect in NC again, google should warn you because NC migration app will access your photo/drive/contacts...
* it should work :grin:

**Comment by portfolioris** [comment]
It's not a bug I think. You need to enable the APIs explicitly in Google. I fixed it by enabling the APIs here: https://console.cloud.google.com/apis/library

**Comment by pnunn** [comment]
I have the api's enabled, but am getting this error also when trying to authenticate.  I've set up a new set of OAuth credentials for NC but still no good.  Any clues?

**Comment by QazCetelic** [comment]
> It seems that you didn't add the required APIs ("Google Drive API", "Google Calendar API", "People API" and "Photos Library API") to your Google OAuth app. Or maybe you connected to your google account in NC while those APIs were not added yet.
> 
> You can try to:
> 
>     * go to any google page (gmail, GDrive...) and log out
> 
>     * make sure you added the APIs in your OAuth app
> 
>     * try to connect in NC again, google should warn you because NC migration app will access your photo/drive/contacts...
> 
>     * it should work grin

I have added the API's and logged out before attempting to authenticate, however it did not work.

**Comment by QazCetelic** [comment]
UPDATE:
I've been able to fix this issue by adding scopes for the API's to the app and adding myself as a tester.

![image](https://user-images.githubusercontent.com/51381523/195432868-ef7dcc56-926e-4813-96b6-4c9e1d53278b.png)

![image](https://user-images.githubusercontent.com/51381523/195433052-7b7eb519-3720-4edb-a0e9-260b9d15d26c.png)

This results in a different message, a warning that with a continue button. However, upon clicking it, I get this.

![image](https://user-images.githubusercontent.com/51381523/195433300-99c62e79-281c-4f8e-8fb4-3c6c3185a1fe.png)
