### ISSUE TITLE
Impossible to refresh the token

### ISSUE THREAD

**Issue by jrial** [nextcloud/integration_google#66]
I've connected the integration to my Google account, but after some days, it stops working. When I go to the data migration page, I don't see my documents/photos/contacts/... sections on the page, but get a blank page where my only option is to disconnect from Google, and some transient warnings about not being able to refresh the token:

![image](https://user-images.githubusercontent.com/570247/125078137-46bcfd00-e0c2-11eb-8767-9ff71e80e7a4.png)

I can disconnect, and reconnect, and everything looks right again:

![image](https://user-images.githubusercontent.com/570247/125078410-a3201c80-e0c2-11eb-856d-f5a9790658fc.png)

But this only lasts for a couple of days, weeks? Eventually it will break again at some point, for reasons unknown.

**Comment by eneiluj** [comment]
Hi, thanks for the bug report.

I never had any problem about refreshing tokens. Let's try to find out what happens on your side.

Could you upgrade to the latest nightly I just published? `v1.0.4-1-nightly`
You can get it with this occ command (adjust to your context):
```
sudo -u www-data php ./occ app:update --allow-unstable integration_google
```
To get back to the official release, just disable, delete and reinstall the app in web app settings.

So, once you're running `v1.0.4-1-nightly` there will be more information in server logs when the token refresh fails. Search for lines looking like `Google API error, impossible to refresh the token. Response: ...`
I also added one dummy request before the Data migration page load, just in case your problem is caused by multiple concurrent token refresh requests.

**Comment by eneiluj** [comment]
By the way, google oauth tokens expire after one hour.

**Comment by jrial** [comment]
I ran that command in the `/var/www/nextcloud/` folder, but it doesn't produce any output, and my app version remains at 1.02. Is there any other way I could apply this update?

**Comment by eneiluj** [comment]
I should have mentioned this nightly is only compatible with NC 22.

Yes there is another way but it will still not work if you're running NC 20 or 21 :grin:.

**Comment by jrial** [comment]
Ah, in that case I can't really debug. My installation tracks the stable channel, so I'm still on 20.

**Comment by eneiluj** [comment]
Too bad. Just in case you are motivated and have some minutes to spare: It is really quick to install a local test instance of 22 using a SQLite database.

**Comment by tomshutterbug** [comment]
I also have this exact same issue - I do have 2FA enabled on my Google Account - that wouldn't be the issue right?

**Comment by richardneish** [comment]
I had this issue, and checked the Google Oauth settings.  In my case my application was in test mode, and promoting it to production made the error disappear.  I will comment again if it re-appears.
