### ISSUE TITLE
white page

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/integration_google#8]
I only get a white page If I go to <mycloud>/settings/user/migration
NC20

console:
No OC found
jQuery is deprecated
$ is deprecated

**Comment by eneiluj** [comment]
It's probably because no admin configuration was done (in connected accounts admin section). If you're an administrator of your Nextcloud instance, go there and follow the procedure to create a Google OAuth app. Then it will show something in the migration section.

If you're not a Nextcloud admin, then ask the admin about that.

**Comment by eneiluj** [comment]
I'll add a message explaining all that in the migration section.

**Comment by jakobroehrl** [comment]
You are right, I tested it. It's working after I set the admin settings. 
A hint would sove this Issue, I thinks. 
Thanks for looking over it.

**Comment by eneiluj** [comment]
There is now a hint if OAuth admin config has not been done. Thanks again for the feedback.
