### ISSUE TITLE
How to avoid file name change

### ISSUE THREAD

**Issue by vhostvn** [nextcloud/integration_google#98]
Hi,

I'm trying this integration, migration is ok but we see significant problem on speed and file name change.

How to increase migration speed?

And avoid append random string to file name like below screenshot?

![image](https://user-images.githubusercontent.com/16444776/155310143-a66590ac-b796-4500-9263-de2cdc5f835e.png)

**Comment by danepowell** [comment]
This is a bit of a hack, but the files seem to follow a naming convention, you could use this shell one-liner to clean them up after the import:
`find . -type f |  sed -n "s/\(.*\)_\(.\{6\}\)\.\(.*\)$/\"&\" \"\1.\3\"/p" | xargs -n 2 mv`

This looks for files of the pattern `foo_abc123.ext` and renames them to `foo.ext`.

**Comment by julien-nc** [comment]
The name suffix was added because google allows multiple files with the same name in a directory...

v1.0.9 (coming soon) will include improvements in this area: the suffix will only be added for files with name conflicts (on the google side).

Regarding the speed, well it's kind of tricky to deal with Php limitations. The import is done by chunks of approx. 500 MB every time NC's cron.php is executed.

Feel free to reopen if needed.
